title: Jiafan Z.

author:
    name: Jiafan
    facebook:
    scholar:

url: "http://jiafanz.github.io"     # the base hostname & protocol for your site
baseurl: ""

permalink: pretty

# Build settings
kramdown:
    input: GFM