title: Geeky corner
description: Much-Worse Jekyll theme for academic page and blog
sourcecode: "https://github.com/gchauras/much-worse-jekyll-theme"

author:
    name: Jiafan
    facebook:
    scholar:

url: "http://jiafanz.github.io"     # the base hostname & protocol for your site
baseurl: ""

permalink: pretty

# Build settings
kramdown:
    input: GFM

# Settings for comments helper
# Set 'provider' to the comment provider you want to use.
# Set 'provider' to false to turn commenting off globally.
#
comments:
    provider:
    disqus:
      short_name:
    livefyre:
      site_id:
    intensedebate:
      account:
    facebook:
      appid:
      num_posts: 5
      width: 580
      colorscheme: light
